version: '2.2'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:latest
        volumes:
            - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        healthcheck:
            test:
                ['CMD', 'curl', '-s', '-f', 'http://localhost:9200/_cat/health']
            interval: 3s
            timeout: 3s
            retries: 10
        ports:
            - 9200:9200
    logstash:
        image: docker.elastic.co/logstash/logstash:latest
        volumes:
            - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        depends_on:
            elasticsearch:
                condition: service_healthy
    golang:
        image: golang:latest
        depends_on:
            elasticsearch:
                condition: service_healthy
        volumes:
            - ./:/go/src/github.com/dazai404/super-logger
            - ./logs/:/logs/
        working_dir: /go/src/github.com/dazai404/super-logger
        command: go run main.go

    filebeat:
        image: docker.elastic.co/beats/filebeat:latest
        depends_on:
            elasticsearch:
                condition: service_healthy
        volumes:
            - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./logs/:/logs/
    kibana:
        image: docker.elastic.co/kibana/kibana:latest
        depends_on:
            elasticsearch:
                condition: service_healthy
        healthcheck:
            test:
                ['CMD', 'curl', '-s', '-f', 'http://localhost:5601/api/status']
            interval: 3s
            timeout: 3s
            retries: 50
        ports:
            - 5601:5601
